commonrepo/elos/urls.py
# -*- coding: utf-8 -*-

#
# Copyright 2016 edX PDR Lab, National Central University, Taiwan.
#
#     http://edxpdrlab.ncu.cc/
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Created By: yrchen@ATCity.org
# Maintained By: yrchen@ATCity.org
#

"""
URLs configurations for ELOs package in Common Repository project.
"""

from __future__ import absolute_import, unicode_literals

from django.conf.urls import url

from . import views


__author__ = 'yrchen@ATCity.org (Xaver Y.R. Chen)'


urlpatterns = [
    # URL pattern for the ELOsMyListView
    url(
        regex=r'^$',
        view=views.ELOsMyListView.as_view(),
        name='elos-mylist'
    ),
    # URL pattern for the ELOsFollowingListView
    url(
        regex=r'^following/$',
        view=views.ELOsFollowingListView.as_view(),
        name='elos-followinglist'
    ),
    # URL pattern for the ELOsDetailView
    url(
        regex=r'^(?P<pk>[0-9]+)/$',
        view=views.ELOsDetailView.as_view(),
        name='elos-detail'
    ),
    # URL pattern for the ELOsListView
    url(
        regex=r'^all/$',
        view=views.ELOsListView.as_view(),
        name="elos-alllist"
    ),
    # URL pattern for the ELOsCreateView
    url(
        regex=r'^create/$',
        view=views.ELOsCreateView.as_view(),
        name="elos-create"
    ),
    # URL pattern for the ELOsForkView
    url(
        regex=r'^fork/(?P<pk>[0-9]+)/$',
        view=views.ELOsForkView.as_view(),
        name="elos-fork"
    ),
    # URL pattern for the ELOsNetworkView
    url(
        regex=r'^netork/(?P<pk>[0-9]+)/$',
        view=views.ELOsNetworkView.as_view(),
        name="elos-network"
    ),
    # URL pattern for the ELOsUpdateView
    url(
        regex=r'^update/(?P<pk>[0-9]+)/$',
        view=views.ELOsUpdateView.as_view(),
        name='elos-update'
    ),
    # URL pattern for the ELOsMetadataUpdateView
    url(
        regex=r'^metadata/update/(?P<pk>[0-9]+)/$',
        view=views.ELOsMetadataUpdateView.as_view(),
        name='elos-metadata-update'
    ),
    # URL pattern for the ELOTypesDetailView
    url(
        regex=r'^type/(?P<pk>[0-9]+)/$',
        view=views.ELOTypesDetailView.as_view(),
        name='elotypes-detail'
    ),
    # URL pattern for the publish ELO action
    url(
        regex=r'^publish/(?P<pk>[0-9]+)/$',
        view=views.publish_elo,
        name='elos-publish'
    ),
    # URL pattern for the unpublish ELO action
    url(
        regex=r'^unpublish/(?P<pk>[0-9]+)/$',
        view=views.unpublish_elo,
        name='elos-unpublish'
    ),
    # URL pattern for the follow ELO action
    url(
        regex=r'^follow/(?P<pk>[0-9]+)/$',
        view=views.follow_elo,
        name='elos-follow'
    ),
    # URL pattern for the unfollow ELO action
    url(
        regex=r'^unfollow/(?P<pk>[0-9]+)/$',
        view=views.unfollow_elo,
        name='elos-unfollow'
    )
]

commonrepo/groups/urls.py
# -*- coding: utf-8 -*-

#
# Copyright 2016 edX PDR Lab, National Central University, Taiwan.
#
#     http://edxpdrlab.ncu.cc/
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Created By: yrchen@ATCity.org
# Maintained By: yrchen@ATCity.org
#

"""
URLs configurations for Groups in Common Repository project.
"""

from __future__ import absolute_import, unicode_literals

from django.conf.urls import url

from . import views


__author__ = 'yrchen@ATCity.org (Xaver Y.R. Chen)'


urlpatterns = [
    # URL pattern for the GroupsAbortView
    url(
        regex=r'^abort/(?P<pk>[0-9]+)/$',
        view=views.GroupsAbortView.as_view(),
        name="groups-abort"
    ),
    # URL pattern for the GroupsListView
    url(
        regex=r'^all/$',
        view=views.GroupsListView.as_view(),
        name="groups-alllist"
    ),
    # URL pattern for the GroupsCreateView
    url(
        regex=r'^create/$',
        view=views.GroupsCreateView.as_view(),
        name="groups-create"
    ),
    # URL pattern for the GroupsDetailView
    url(
        regex=r'^(?P<pk>[0-9]+)/$',
        view=views.GroupsDetailView.as_view(),
        name='groups-detail'
    ),
    # URL pattern for the GroupsJoinView
    url(
        regex=r'^join/(?P<pk>[0-9]+)/$',
        view=views.GroupsJoinView.as_view(),
        name="groups-join"
    ),
    # URL pattern for the GroupsMyListView
    url(
        regex=r'^$',
        view=views.GroupsMyListView.as_view(),
        name='groups-mylist'
    ),
    # URL pattern for the GroupsFollowingListView
    url(
        regex=r'^following/$',
        view=views.GroupsFollowingListView.as_view(),
        name='groups-followinglist'
    ),
    # URL pattern for the GroupsUpdateView
    url(
        regex=r'^update/(?P<pk>[0-9]+)/$',
        view=views.GroupsUpdateView.as_view(),
        name='groups-update'
    ),
    # URL pattern for the follow Group action
    url(
        regex=r'^follow/(?P<pk>[0-9]+)/$',
        view=views.follow_group,
        name='groups-follow'
    ),
    # URL pattern for the unfollow Group action
    url(
        regex=r'^unfollow/(?P<pk>[0-9]+)/$',
        view=views.unfollow_group,
        name='groups-unfollow'
    ),
]

commonrepo/users/urls.py
# -*- coding: utf-8 -*-

#
# Copyright 2016 edX PDR Lab, National Central University, Taiwan.
#
#     http://edxpdrlab.ncu.cc/
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Created By: yrchen@ATCity.org
# Maintained By: yrchen@ATCity.org
#

"""
URLs configurations for Users in Common Repository project.
"""

from __future__ import absolute_import, unicode_literals
from django.conf.urls import url

from . import views


__author__ = 'yrchen@ATCity.org (Xaver Y.R. Chen)'


urlpatterns = [
    # URL pattern for the UserListView
    url(
        regex=r'^$',
        view=views.UserListView.as_view(),
        name='list'
    ),

    # URL pattern for the UserRedirectView
    url(
        regex=r'^~redirect/$',
        view=views.UserRedirectView.as_view(),
        name='redirect'
    ),

    # URL pattern for the UserDetailView
    url(
        regex=r'^(?P<username>[\w.@+-]+)/$',
        view=views.UserDetailView.as_view(),
        name='detail'
    ),

    # URL pattern for the UserUpdateView
    url(
        regex=r'^~update/$',
        view=views.UserUpdateView.as_view(),
        name='update'
    ),

    # URL for follow and unfollow user
    url(
        regex=r'^(?P<username>[\w.@+-]+)/follow/$',
        view=views.follow_user,
        name='follow'
    ),
    url(
        regex=r'^(?P<username>[\w.@+-]+)/unfollow/$',
        view=views.unfollow_user,
        name='unfollow'
    ),

    # URL for check user's follower and following list
    url(
        regex=r'^(?P<username>[\w.@+-]+)/followers/$',
        view=views.UserFollowerView.as_view(),
        name='followers'
    ),
    url(
        regex=r'^(?P<username>[\w.@+-]+)/following/$',
        view=views.UserFollowingView.as_view(),
        name='following'
    ),

    # URL for check user's ELOs
    url(
        regex=r'^(?P<username>[\w.@+-]+)/elos/$',
        view=views.UserELOsListView.as_view(),
        name='elos'
    ),
]

config/urls.py
# -*- coding: utf-8 -*-

#
# Copyright 2016 edX PDR Lab, National Central University, Taiwan.
#
#     http://edxpdrlab.ncu.cc/
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Created By: yrchen@ATCity.org
# Maintained By: yrchen@ATCity.org
#

"""
URLs for Common Repository project.
http://www.commonrepo.com/
"""
from __future__ import unicode_literals

from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.views.generic import TemplateView

from filebrowser.sites import site

from rest_framework.authtoken.views import obtain_auth_token
from rest_framework.urlpatterns import format_suffix_patterns

from commonrepo.api.routers import DefaultRouter
from commonrepo.elos_api.views import ELOViewSet, ELOViewSetV2, ELOTypeViewSet, ELOFileUploadViewSet
from commonrepo.elos_api.views import ELODiversity, ELODiversityAll, ELOSimilarity, ELOSimilarityAll, ELOFork
from commonrepo.infor_api.views import InforELOTotalCount, InforUsersTotalCount
from commonrepo.groups_api.views import GroupViewSet, GroupViewSetV2
from commonrepo.groups_api.views import GroupsMemberAbort, GroupsMemberJoin
from commonrepo.main import views as MainViews
from commonrepo.snippets_api.views import SnippetViewSet
from commonrepo.users_api.views import UserViewSet, UserViewSetV2

#
# API v1
#
router_api_v1 = DefaultRouter()
router_api_v1.register(r'api/v1/elos', ELOViewSet)
router_api_v1.register(r'api/v1/elotypes', ELOTypeViewSet)
router_api_v1.register(r'api/v1/groups', GroupViewSet)
router_api_v1.register(r'api/v1/snippets', SnippetViewSet)
router_api_v1.register(r'api/v1/users', UserViewSet)

#
# API v2
#
router_api_v2 = DefaultRouter()
router_api_v2.register(r'api/v2/elos', ELOViewSetV2)
router_api_v2.register(r'api/v2/groups', GroupViewSetV2)
router_api_v2.register(r'api/v2/users', UserViewSetV2)

urlpatterns = [
    url(r'^$', TemplateView.as_view(template_name='pages/home.html'), name="home"),
    url(r'^about/$', TemplateView.as_view(template_name='pages/about.html'), name="about"),
    url(r'^download/$', TemplateView.as_view(template_name='pages/download.html'), name="download"),

    url(r'^dashboard/$', MainViews.DashboardView.as_view(), name="dashboard"),

    # Django Admin
    url(r'^admin/filebrowser/', include(site.urls)),  # django-filebrowser
    url(r'^grappelli/', include('grappelli.urls')),  # grappelli URLS
    url(r'^admin/', include(admin.site.urls)),

    # User management
    url(r'^users/', include("commonrepo.users.urls", namespace="users")),
    url(r'^accounts/', include('allauth.urls')),
    url(r'^avatar/', include('avatar.urls')),

    # Message
    url(r'^messages/', include('messages_extends.urls')),  # django-messages-extends

    # Notifications
    url(r'^notifications/', include('notifications.urls', namespace='notifications')),

    # Activity
    url('^activity/', include('actstream.urls')),  # django-activity-stream

    # Comments
    url(r'^comments/', include('fluent_comments.urls')),  # django-contrib-comments

    # Documents
    url(r'^api/docs/', include('rest_framework_swagger.urls')),  # django-rest-swagger

    # Files
    url(r'^files/', include('filer.urls')),

    # Search
    url(r'^search/', include('haystack.urls'), name="search"),  # django-haystack

    # Your stuff: custom urls includes go here
    url(r'^elos/', include("commonrepo.elos.urls", namespace="elos")),
    url(r'^groups/', include("commonrepo.groups.urls", namespace="groups")),

    # Django REST Framework (DRF) Authenticaion
    url(r'^api/drf/auth/', include('rest_framework.urls', namespace='rest_framework')),
    url(r'^api/oauth2/', include('oauth2_provider.urls', namespace='oauth2_provider')),

    #
    # API v1
    #

    # API v1 - Endpoints
    url(r'', include(router_api_v1.urls)),


    # API v1 - Authenticaion
    url(r'^api/v1/auth/', include('djoser.urls.authtoken')),

    # API v1 - ELOs
    url(r'^api/v1/elos-upload', ELOFileUploadViewSet),
    url(r'^api/v1/elos/diversity/(?P<pk>[0-9]+)/(?P<pk2>[0-9]+)/$', 'commonrepo.elos_api.views.elos_diversity'),
    url(r'^api/v1/elos/diversity/(?P<pk>[0-9]+)/all/$', 'commonrepo.elos_api.views.elos_diversity_all'),
    url(r'^api/v1/elos/similarity/(?P<pk>[0-9]+)/(?P<pk2>[0-9]+)/$', 'commonrepo.elos_api.views.elos_similarity'),
    url(r'^api/v1/elos/similarity/(?P<pk>[0-9]+)/all/$', 'commonrepo.elos_api.views.elos_similarity_all'),
    url(r'^api/v1/elos/fork/(?P<pk>[0-9]+)/$', 'commonrepo.elos_api.views.elos_fork'),

    # API v1 - Information
    url(r'^api/v1/infor/elos-total/$', 'commonrepo.infor_api.views.elos_total_count'),
    url(r'^api/v1/infor/users-total/$', 'commonrepo.infor_api.views.users_total_count'),

    # API v1 - Groups
    url(r'^api/v1/groups/abort/(?P<pk>[0-9]+)/$', 'commonrepo.groups_api.views.groups_member_abort'),
    url(r'^api/v1/groups/join/(?P<pk>[0-9]+)/$', 'commonrepo.groups_api.views.groups_member_join'),

    #
    # API v2
    #

    # API v2 - Endpoints
    url(r'', include(router_api_v2.urls)),

    # API v2 - Authenticaion
    url(r'^api/v2/auth/', include('djoser.urls.authtoken')),

    # API v2 - ELOs
    url(r'^api/v2/elos-upload', ELOFileUploadViewSet),
    url(r'^api/v2/elos/diversity/(?P<pk>[0-9]+)/(?P<pk2>[0-9]+)/$', ELODiversity.as_view()),
    url(r'^api/v2/elos/diversity/(?P<pk>[0-9]+)/all/$', ELODiversityAll.as_view()),
    url(r'^api/v2/elos/similarity/(?P<pk>[0-9]+)/(?P<pk2>[0-9]+)/$', ELOSimilarity.as_view()),
    url(r'^api/v2/elos/similarity/(?P<pk>[0-9]+)/all/$', ELOSimilarityAll.as_view()),
    url(r'^api/v2/elos/fork/(?P<pk>[0-9]+)/$', ELOFork.as_view()),

    # API v2 - Information
    url(r'^api/v2/infor/elos-total/$', InforELOTotalCount.as_view()),
    url(r'^api/v2/infor/users-total/$', InforUsersTotalCount.as_view()),

    # API v2 - Groups
    url(r'^api/v2/groups/abort/(?P<pk>[0-9]+)/$', GroupsMemberAbort.as_view()),
    url(r'^api/v2/groups/join/(?P<pk>[0-9]+)/$', GroupsMemberJoin.as_view()),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        url(r'^400/$', 'django.views.defaults.bad_request'),
        url(r'^403/$', 'django.views.defaults.permission_denied'),
        url(r'^404/$', 'django.views.defaults.page_not_found'),
        url(r'^500/$', 'django.views.defaults.server_error'),
    ]

commonrepo/snippets_api/views.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, unicode_literals

from django.http import HttpResponse
from django.views.decorators.csrf import csrf_exempt

from rest_framework import permissions
from rest_framework import renderers
from rest_framework import viewsets
from rest_framework.decorators import detail_route
from rest_framework.renderers import JSONRenderer
from rest_framework.response import Response
from rest_framework.parsers import JSONParser

from commonrepo.users.models import User as User

from .models import Snippet
from .permissions import IsOwnerOrReadOnly
from .serializers import SnippetSerializer


class SnippetViewSet(viewsets.ModelViewSet):
    """
    This endpoint presents code snippets.

    The `highlight` field presents a hyperlink to the hightlighted HTML
    representation of the code snippet.

    The **owner** of the code snippet may update or delete instances
    of the code snippet.

    Try it yourself by logging in as one of these four users: **amy**, **max**,
    **jose** or **aziz**.  The passwords are the same as the usernames.
    """
    queryset = Snippet.objects.all()
    serializer_class = SnippetSerializer
    permission_classes = (permissions.IsAuthenticatedOrReadOnly,
                          IsOwnerOrReadOnly,)

    @detail_route(renderer_classes=(renderers.StaticHTMLRenderer,))
    def highlight(self, request, *args, **kwargs):
        snippet = self.get_object()
        return Response(snippet.highlighted)

    def perform_create(self, serializer):
        serializer.save(owner=self.request.user)

commonrepo/templates/widgets/footer.html
{% load commonrepo_tags %}

<footer class="main-footer">
  <!-- To the right -->
  <div class="pull-right hidden-xs">
    <b>Version</b> {% get_settings_value "VERSION" %}
  </div>
  <!-- Default to the left -->
  <strong>Copyright &copy; 2015-2016 <a href="http://edxpdrlab.ncu.cc">NCU Open edX PDR Lab</a>.</strong> All rights reserved.
</footer>

commonrepo/templates/widgets/menu-messages.html
{% load static %}

<li class="dropdown messages-menu">
  <!-- Menu toggle button -->
  <a href="#" class="dropdown-toggle" data-toggle="dropdown">
    <i class="fa fa-envelope-o"></i>
    <span class="label label-success">4</span>
  </a>
  <ul class="dropdown-menu">
    <li class="header">You have 4 messages</li>
    <li>
      <!-- inner menu: contains the messages -->
      <ul class="menu">
        <li><!-- start message -->
          <a href="#">
            <div class="pull-left">
              <!-- User Image -->
              <img src="{% static "AdminLTE/img/user2-160x160.jpg" %}" class="img-circle" alt="User Image">
            </div>
            <!-- Message title and timestamp -->
            <h4>
              Support Team
              <small><i class="fa fa-clock-o"></i> 5 mins</small>
            </h4>
            <!-- The message -->
            <p>Why not buy a new awesome theme?</p>
          </a>
        </li><!-- end message -->
      </ul><!-- /.menu -->
    </li>
    <li class="footer"><a href="#">See All Messages</a></li>
  </ul>
</li><!-- /.messages-menu -->

commonrepo/templates/widgets/menu-user.html
{% load avatar_tags %}
{% load static %}

{% load commonrepo_tags %}

<li class="dropdown user user-menu">
  <!-- Menu Toggle Button -->
  <a href="#" class="dropdown-toggle" data-toggle="dropdown">
    <!-- The user image in the navbar-->
    {% if request.user.is_authenticated %}
    <img src="{% avatar_url request.user %}" class="user-image" alt="User Image">
    <!-- hidden-xs hides the username on small devices so only the image appears. -->
    <span class="hidden-xs">{{ request.user.username }}</span>
    {% else %}
    <img src="{% static "AdminLTE/img/user2-160x160.jpg" %}" class="user-image" alt="Guest User Image">
    <span class="hidden-xs">Guest</span>
    {% endif %}
  </a>
  <ul class="dropdown-menu">
    <!-- The user image in the menu -->
    <li class="user-header">
      {% if request.user.is_authenticated %}
      <img src="{% avatar_url request.user %}" class="img-circle" alt="User Image">
      <p>
        Welcome, {{ request.user.username }}
        <small>Member since {{ request.user.date_joined }}</small>
      </p>
      {% else %}
      <img src="{% static "AdminLTE/img/user2-160x160.jpg" %}" class="user-image" alt="Guest User Image">
      <p>Welcome, new user. Please log in.</p>
      {% endif %}      
    </li>
    <!-- Menu Body -->
    <li class="user-body">
      {% if request.user.is_authenticated %}
      <div class="col-xs-6 text-center">
        <a href="{% url 'users:followers' request.user %}">{% get_user_followers_count request.user %} Followers</a>
      </div>
      <div class="col-xs-6 text-center">
        <a href="#">{% get_user_friends_count request.user %} Friends</a>
      </div>
      {% endif %}
    </li>
    <!-- Menu Footer-->
    <li class="user-footer">
      {% if request.user.is_authenticated %}
      <div class="pull-left">
        <a href="{% url 'users:detail' request.user.username  %}" class="btn btn-default btn-flat">Profile</a>
      </div>
      <div class="pull-right">
        <a href="{% url 'account_logout' %}" class="btn btn-default btn-flat">Sign out</a>
      </div>
      {% else %}
      <div class="pull-left">
        <a href="{% url 'account_login' %}" class="btn btn-default btn-flat">Log In</a>
      </div>
      <div class="pull-right">
        <a href="{% url 'account_signup' %}" class="btn btn-default btn-flat">Sign up</a>
      </div>
      {% endif %}
    </li>
  </ul>
</li>

commonrepo/templates/widgets/sidebar-default.html
{% load avatar_tags %}
{% load static %}

<aside class="main-sidebar">

  <!-- sidebar: style can be found in sidebar.less -->
  <section class="sidebar">
    <!-- Sidebar Menu -->
    <ul class="sidebar-menu">
      <li class="header">Main Navigation</li>
      <!-- Optionally, you can add icons to the links -->
      <li><a href="{% url 'dashboard' %}"><i class="fa fa-dashboard"></i> <span>Dashboard</span></a></li>
      <li class="active treeview">
        <a href="#"><i class="fa fa-book"></i> <span>ELOs</span> <i class="fa fa-angle-left pull-right"></i></a>
        <ul class="treeview-menu">
          <li><a href="{% url 'elos:elos-mylist' %}"><i class="fa fa-link"></i> <span>My ELOs</span></a></li>
          <li><a href="{% url 'elos:elos-alllist' %}"><i class="fa fa-link"></i> <span>All ELOs</span></a></li>
        </ul>
      </li>
      <li class="active treeview">
        <a href="#"><i class="fa fa-users"></i> <span>Groups</span> <i class="fa fa-angle-left pull-right"></i></a>
        <ul class="treeview-menu">
          <li><a href="{% url 'groups:groups-mylist' %}"><i class="fa fa-link"></i> <span>My Groups</span></a></li>
          <li><a href="{% url 'groups:groups-alllist' %}"><i class="fa fa-link"></i> <span>All Groups</span></a></li>
        </ul>
      </li>
      <li><a href="{% url 'about' %}"><i class="fa fa-flag"></i> <span>About</span></a></li>
    </ul><!-- /.sidebar-menu -->
  </section>
  <!-- /.sidebar -->
</aside>

commonrepo/templates/widgets/sidebar-main.html
{% load avatar_tags %}
{% load static %}

<aside class="main-sidebar">

  <!-- sidebar: style can be found in sidebar.less -->
  <section class="sidebar">

    <!-- Sidebar user panel (optional) -->
    <div class="user-panel">
      <div class="pull-left image">
        {% if request.user.is_authenticated %}
        <img src="{% avatar_url request.user %}" class="img-circle" alt="User Image">
        {% else %}
        <img src="{% static "AdminLTE/img/user2-160x160.jpg" %}" class="user-image" alt="Guest User Image">
        {% endif %}
      </div>
      <div class="pull-left info">
        {% if request.user.is_authenticated %}
          {% if request.user.name%}
            <p>{{ request.user.name }}</p>
          {% else %}
            <p>{{ request.user.username }}</p>
          {% endif %}
        {% else %}
        <p>Guest</p>
        {% endif %}
        <!-- Status -->
        <a href="#"><i class="fa fa-circle text-success"></i> Online</a>
      </div>
    </div>

    <!-- search form (Optional) -->
    <form action="{% url 'haystack_search' %}" method="get" class="sidebar-form">
      <div class="input-group">
        <input type="text" name="q" class="form-control" placeholder="Search...">
        <span class="input-group-btn">
          <button type="submit" name="search" id="search-btn" class="btn btn-flat"><i class="fa fa-search"></i></button>
        </span>
      </div>
    </form>
    <!-- /.search form -->

    <!-- Sidebar Menu -->
    <ul class="sidebar-menu">
      <li class="header">Main Navigation</li>
      <!-- Optionally, you can add icons to the links -->
      <li><a href="{% url 'dashboard' %}"><i class="fa fa-dashboard"></i> <span>Dashboard</span></a></li>
      <li class="active treeview">
        <a href="#"><i class="fa fa-user"></i> <span>Users</span> <i class="fa fa-angle-left pull-right"></i></a>
        <ul class="treeview-menu">
          <li><a href="{% url 'users:followers' request.user %}"><i class="fa fa-link"></i> <span>My Followers</span></a></li>
          <li><a href="{% url 'users:following' request.user %}"><i class="fa fa-link"></i> <span>My Following Users</span></a></li>
        </ul>
      </li>
      <li class="active treeview">
        <a href="#"><i class="fa fa-book"></i> <span>ELOs</span> <i class="fa fa-angle-left pull-right"></i></a>
        <ul class="treeview-menu">
          <li><a href="{% url 'elos:elos-mylist' %}"><i class="fa fa-link"></i> <span>My ELOs</span></a></li>
          <li><a href="{% url 'elos:elos-followinglist' %}"><i class="fa fa-link"></i> <span>My Following ELOs</span></a></li>
          <li><a href="{% url 'elos:elos-alllist' %}"><i class="fa fa-link"></i> <span>All ELOs</span></a></li>
        </ul>
      </li>
      <li class="active treeview">
        <a href="#"><i class="fa fa-users"></i> <span>Groups</span> <i class="fa fa-angle-left pull-right"></i></a>
        <ul class="treeview-menu">
          <li><a href="{% url 'groups:groups-mylist' %}"><i class="fa fa-link"></i> <span>My Groups</span></a></li>
          <li><a href="{% url 'groups:groups-followinglist' %}"><i class="fa fa-link"></i> <span>My Following Groups</span></a></li>
          <li><a href="{% url 'groups:groups-alllist' %}"><i class="fa fa-link"></i> <span>All Groups</span></a></li>
        </ul>
      </li>
      <li><a href="{% url 'about' %}"><i class="fa fa-flag"></i> <span>About</span></a></li>
    </ul><!-- /.sidebar-menu -->
  </section>
  <!-- /.sidebar -->
</aside>