commonrepo/elos/urls.py
# -*- coding: utf-8 -*-

#
# Copyright 2016 edX PDR Lab, National Central University, Taiwan.
#
#     http://edxpdrlab.ncu.cc/
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Created By: yrchen@ATCity.org
# Maintained By: yrchen@ATCity.org
#

"""
URLs configurations for ELOs package in Common Repository project.
"""

from __future__ import absolute_import, unicode_literals

from django.conf.urls import url

from . import views


__author__ = 'yrchen@ATCity.org (Xaver Y.R. Chen)'


urlpatterns = [
    # URL pattern for the ELOsMyListView
    url(
        regex=r'^$',
        view=views.ELOsMyListView.as_view(),
        name='elos-mylist'
    ),
    # URL pattern for the ELOsFollowingListView
    url(
        regex=r'^following/$',
        view=views.ELOsFollowingListView.as_view(),
        name='elos-followinglist'
    ),
    # URL pattern for the ELOsDetailView
    url(
        regex=r'^(?P<pk>[0-9]+)/$',
        view=views.ELOsDetailView.as_view(),
        name='elos-detail'
    ),
    # URL pattern for the ELOsListView
    url(
        regex=r'^all/$',
        view=views.ELOsListView.as_view(),
        name="elos-alllist"
    ),
    # URL pattern for the ELOsCreateView
    url(
        regex=r'^create/$',
        view=views.ELOsCreateView.as_view(),
        name="elos-create"
    ),
    # URL pattern for the ELOsForkView
    url(
        regex=r'^fork/(?P<pk>[0-9]+)/$',
        view=views.ELOsForkView.as_view(),
        name="elos-fork"
    ),
    # URL pattern for the ELOsNetworkView
    url(
        regex=r'^netork/(?P<pk>[0-9]+)/$',
        view=views.ELOsNetworkView.as_view(),
        name="elos-network"
    ),
    # URL pattern for the ELOsUpdateView
    url(
        regex=r'^update/(?P<pk>[0-9]+)/$',
        view=views.ELOsUpdateView.as_view(),
        name='elos-update'
    ),
    # URL pattern for the ELOsMetadataUpdateView
    url(
        regex=r'^metadata/update/(?P<pk>[0-9]+)/$',
        view=views.ELOsMetadataUpdateView.as_view(),
        name='elos-metadata-update'
    ),
    # URL pattern for the ELOTypesDetailView
    url(
        regex=r'^type/(?P<pk>[0-9]+)/$',
        view=views.ELOTypesDetailView.as_view(),
        name='elotypes-detail'
    ),
    # URL pattern for the publish ELO action
    url(
        regex=r'^publish/(?P<pk>[0-9]+)/$',
        view=views.publish_elo,
        name='elos-publish'
    ),
    # URL pattern for the unpublish ELO action
    url(
        regex=r'^unpublish/(?P<pk>[0-9]+)/$',
        view=views.unpublish_elo,
        name='elos-unpublish'
    ),
    # URL pattern for the follow ELO action
    url(
        regex=r'^follow/(?P<pk>[0-9]+)/$',
        view=views.follow_elo,
        name='elos-follow'
    ),
    # URL pattern for the unfollow ELO action
    url(
        regex=r'^unfollow/(?P<pk>[0-9]+)/$',
        view=views.unfollow_elo,
        name='elos-unfollow'
    )
]

commonrepo/groups/urls.py
# -*- coding: utf-8 -*-

#
# Copyright 2016 edX PDR Lab, National Central University, Taiwan.
#
#     http://edxpdrlab.ncu.cc/
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Created By: yrchen@ATCity.org
# Maintained By: yrchen@ATCity.org
#

"""
URLs configurations for Groups in Common Repository project.
"""

from __future__ import absolute_import, unicode_literals

from django.conf.urls import url

from . import views


__author__ = 'yrchen@ATCity.org (Xaver Y.R. Chen)'


urlpatterns = [
    # URL pattern for the GroupsAbortView
    url(
        regex=r'^abort/(?P<pk>[0-9]+)/$',
        view=views.GroupsAbortView.as_view(),
        name="groups-abort"
    ),
    # URL pattern for the GroupsListView
    url(
        regex=r'^all/$',
        view=views.GroupsListView.as_view(),
        name="groups-alllist"
    ),
    # URL pattern for the GroupsCreateView
    url(
        regex=r'^create/$',
        view=views.GroupsCreateView.as_view(),
        name="groups-create"
    ),
    # URL pattern for the GroupsDetailView
    url(
        regex=r'^(?P<pk>[0-9]+)/$',
        view=views.GroupsDetailView.as_view(),
        name='groups-detail'
    ),
    # URL pattern for the GroupsJoinView
    url(
        regex=r'^join/(?P<pk>[0-9]+)/$',
        view=views.GroupsJoinView.as_view(),
        name="groups-join"
    ),
    # URL pattern for the GroupsMyListView
    url(
        regex=r'^$',
        view=views.GroupsMyListView.as_view(),
        name='groups-mylist'
    ),
    # URL pattern for the GroupsFollowingListView
    url(
        regex=r'^following/$',
        view=views.GroupsFollowingListView.as_view(),
        name='groups-followinglist'
    ),
    # URL pattern for the GroupsUpdateView
    url(
        regex=r'^update/(?P<pk>[0-9]+)/$',
        view=views.GroupsUpdateView.as_view(),
        name='groups-update'
    ),
    # URL pattern for the follow Group action
    url(
        regex=r'^follow/(?P<pk>[0-9]+)/$',
        view=views.follow_group,
        name='groups-follow'
    ),
    # URL pattern for the unfollow Group action
    url(
        regex=r'^unfollow/(?P<pk>[0-9]+)/$',
        view=views.unfollow_group,
        name='groups-unfollow'
    ),
]

commonrepo/users/urls.py
# -*- coding: utf-8 -*-

#
# Copyright 2016 edX PDR Lab, National Central University, Taiwan.
#
#     http://edxpdrlab.ncu.cc/
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Created By: yrchen@ATCity.org
# Maintained By: yrchen@ATCity.org
#

"""
URLs configurations for Users in Common Repository project.
"""

from __future__ import absolute_import, unicode_literals
from django.conf.urls import url

from . import views


__author__ = 'yrchen@ATCity.org (Xaver Y.R. Chen)'


urlpatterns = [
    # URL pattern for the UserListView
    url(
        regex=r'^$',
        view=views.UserListView.as_view(),
        name='list'
    ),

    # URL pattern for the UserRedirectView
    url(
        regex=r'^~redirect/$',
        view=views.UserRedirectView.as_view(),
        name='redirect'
    ),

    # URL pattern for the UserDetailView
    url(
        regex=r'^(?P<username>[\w.@+-]+)/$',
        view=views.UserDetailView.as_view(),
        name='detail'
    ),

    # URL pattern for the UserUpdateView
    url(
        regex=r'^~update/$',
        view=views.UserUpdateView.as_view(),
        name='update'
    ),

    # URL for follow and unfollow user
    url(
        regex=r'^(?P<username>[\w.@+-]+)/follow/$',
        view=views.follow_user,
        name='follow'
    ),
    url(
        regex=r'^(?P<username>[\w.@+-]+)/unfollow/$',
        view=views.unfollow_user,
        name='unfollow'
    ),

    # URL for check user's follower and following list
    url(
        regex=r'^(?P<username>[\w.@+-]+)/followers/$',
        view=views.UserFollowerView.as_view(),
        name='followers'
    ),
    url(
        regex=r'^(?P<username>[\w.@+-]+)/following/$',
        view=views.UserFollowingView.as_view(),
        name='following'
    ),

    # URL for check user's ELOs
    url(
        regex=r'^(?P<username>[\w.@+-]+)/elos/$',
        view=views.UserELOsListView.as_view(),
        name='elos'
    ),
]

config/urls.py
# -*- coding: utf-8 -*-

#
# Copyright 2016 edX PDR Lab, National Central University, Taiwan.
#
#     http://edxpdrlab.ncu.cc/
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Created By: yrchen@ATCity.org
# Maintained By: yrchen@ATCity.org
#

"""
URLs for Common Repository project.
http://www.commonrepo.com/
"""
from __future__ import unicode_literals

from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.views.generic import TemplateView

from filebrowser.sites import site

from rest_framework.authtoken.views import obtain_auth_token
from rest_framework.urlpatterns import format_suffix_patterns

from commonrepo.api.routers import DefaultRouter
from commonrepo.elos_api.views import ELOViewSet, ELOViewSetV2, ELOTypeViewSet, ELOFileUploadViewSet
from commonrepo.elos_api.views import ELODiversity, ELODiversityAll, ELOSimilarity, ELOSimilarityAll, ELOFork
from commonrepo.infor_api.views import InforELOTotalCount, InforUsersTotalCount
from commonrepo.groups_api.views import GroupViewSet, GroupViewSetV2
from commonrepo.groups_api.views import GroupsMemberAbort, GroupsMemberJoin
from commonrepo.main import views as MainViews
from commonrepo.snippets_api.views import SnippetViewSet
from commonrepo.users_api.views import UserViewSet, UserViewSetV2

#
# API v1
#
router_api_v1 = DefaultRouter()
router_api_v1.register(r'api/v1/elos', ELOViewSet)
router_api_v1.register(r'api/v1/elotypes', ELOTypeViewSet)
router_api_v1.register(r'api/v1/groups', GroupViewSet)
router_api_v1.register(r'api/v1/snippets', SnippetViewSet)
router_api_v1.register(r'api/v1/users', UserViewSet)

#
# API v2
#
router_api_v2 = DefaultRouter()
router_api_v2.register(r'api/v2/elos', ELOViewSetV2)
router_api_v2.register(r'api/v2/groups', GroupViewSetV2)
router_api_v2.register(r'api/v2/users', UserViewSetV2)

urlpatterns = [
    url(r'^$', TemplateView.as_view(template_name='pages/home.html'), name="home"),
    url(r'^about/$', TemplateView.as_view(template_name='pages/about.html'), name="about"),
    url(r'^download/$', TemplateView.as_view(template_name='pages/download.html'), name="download"),

    url(r'^dashboard/$', MainViews.DashboardView.as_view(), name="dashboard"),

    # Django Admin
    url(r'^admin/filebrowser/', include(site.urls)),  # django-filebrowser
    url(r'^grappelli/', include('grappelli.urls')),  # grappelli URLS
    url(r'^admin/', include(admin.site.urls)),

    # User management
    url(r'^users/', include("commonrepo.users.urls", namespace="users")),
    url(r'^accounts/', include('allauth.urls')),
    url(r'^avatar/', include('avatar.urls')),

    # Message
    url(r'^messages/', include('messages_extends.urls')),  # django-messages-extends

    # Notifications
    url(r'^notifications/', include('notifications.urls', namespace='notifications')),

    # Activity
    url('^activity/', include('actstream.urls')),  # django-activity-stream

    # Comments
    url(r'^comments/', include('fluent_comments.urls')),  # django-contrib-comments

    # Documents
    url(r'^api/docs/', include('rest_framework_swagger.urls')),  # django-rest-swagger

    # Files
    url(r'^files/', include('filer.urls')),

    # Search
    url(r'^search/', include('haystack.urls'), name="search"),  # django-haystack

    # Your stuff: custom urls includes go here
    url(r'^elos/', include("commonrepo.elos.urls", namespace="elos")),
    url(r'^groups/', include("commonrepo.groups.urls", namespace="groups")),

    # Django REST Framework (DRF) Authenticaion
    url(r'^api/drf/auth/', include('rest_framework.urls', namespace='rest_framework')),
    url(r'^api/oauth2/', include('oauth2_provider.urls', namespace='oauth2_provider')),

    #
    # API v1
    #

    # API v1 - Endpoints
    url(r'', include(router_api_v1.urls)),


    # API v1 - Authenticaion
    url(r'^api/v1/auth/', include('djoser.urls.authtoken')),

    # API v1 - ELOs
    url(r'^api/v1/elos-upload', ELOFileUploadViewSet),
    url(r'^api/v1/elos/diversity/(?P<pk>[0-9]+)/(?P<pk2>[0-9]+)/$', 'commonrepo.elos_api.views.elos_diversity'),
    url(r'^api/v1/elos/diversity/(?P<pk>[0-9]+)/all/$', 'commonrepo.elos_api.views.elos_diversity_all'),
    url(r'^api/v1/elos/similarity/(?P<pk>[0-9]+)/(?P<pk2>[0-9]+)/$', 'commonrepo.elos_api.views.elos_similarity'),
    url(r'^api/v1/elos/similarity/(?P<pk>[0-9]+)/all/$', 'commonrepo.elos_api.views.elos_similarity_all'),
    url(r'^api/v1/elos/fork/(?P<pk>[0-9]+)/$', 'commonrepo.elos_api.views.elos_fork'),

    # API v1 - Information
    url(r'^api/v1/infor/elos-total/$', 'commonrepo.infor_api.views.elos_total_count'),
    url(r'^api/v1/infor/users-total/$', 'commonrepo.infor_api.views.users_total_count'),

    # API v1 - Groups
    url(r'^api/v1/groups/abort/(?P<pk>[0-9]+)/$', 'commonrepo.groups_api.views.groups_member_abort'),
    url(r'^api/v1/groups/join/(?P<pk>[0-9]+)/$', 'commonrepo.groups_api.views.groups_member_join'),

    #
    # API v2
    #

    # API v2 - Endpoints
    url(r'', include(router_api_v2.urls)),

    # API v2 - Authenticaion
    url(r'^api/v2/auth/', include('djoser.urls.authtoken')),

    # API v2 - ELOs
    url(r'^api/v2/elos-upload', ELOFileUploadViewSet),
    url(r'^api/v2/elos/diversity/(?P<pk>[0-9]+)/(?P<pk2>[0-9]+)/$', ELODiversity.as_view()),
    url(r'^api/v2/elos/diversity/(?P<pk>[0-9]+)/all/$', ELODiversityAll.as_view()),
    url(r'^api/v2/elos/similarity/(?P<pk>[0-9]+)/(?P<pk2>[0-9]+)/$', ELOSimilarity.as_view()),
    url(r'^api/v2/elos/similarity/(?P<pk>[0-9]+)/all/$', ELOSimilarityAll.as_view()),
    url(r'^api/v2/elos/fork/(?P<pk>[0-9]+)/$', ELOFork.as_view()),

    # API v2 - Information
    url(r'^api/v2/infor/elos-total/$', InforELOTotalCount.as_view()),
    url(r'^api/v2/infor/users-total/$', InforUsersTotalCount.as_view()),

    # API v2 - Groups
    url(r'^api/v2/groups/abort/(?P<pk>[0-9]+)/$', GroupsMemberAbort.as_view()),
    url(r'^api/v2/groups/join/(?P<pk>[0-9]+)/$', GroupsMemberJoin.as_view()),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        url(r'^400/$', 'django.views.defaults.bad_request'),
        url(r'^403/$', 'django.views.defaults.permission_denied'),
        url(r'^404/$', 'django.views.defaults.page_not_found'),
        url(r'^500/$', 'django.views.defaults.server_error'),
    ]

commonrepo/snippets_api/views.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, unicode_literals

from django.http import HttpResponse
from django.views.decorators.csrf import csrf_exempt

from rest_framework import permissions
from rest_framework import renderers
from rest_framework import viewsets
from rest_framework.decorators import detail_route
from rest_framework.renderers import JSONRenderer
from rest_framework.response import Response
from rest_framework.parsers import JSONParser

from commonrepo.users.models import User as User

from .models import Snippet
from .permissions import IsOwnerOrReadOnly
from .serializers import SnippetSerializer


class SnippetViewSet(viewsets.ModelViewSet):
    """
    This endpoint presents code snippets.

    The `highlight` field presents a hyperlink to the hightlighted HTML
    representation of the code snippet.

    The **owner** of the code snippet may update or delete instances
    of the code snippet.

    Try it yourself by logging in as one of these four users: **amy**, **max**,
    **jose** or **aziz**.  The passwords are the same as the usernames.
    """
    queryset = Snippet.objects.all()
    serializer_class = SnippetSerializer
    permission_classes = (permissions.IsAuthenticatedOrReadOnly,
                          IsOwnerOrReadOnly,)

    @detail_route(renderer_classes=(renderers.StaticHTMLRenderer,))
    def highlight(self, request, *args, **kwargs):
        snippet = self.get_object()
        return Response(snippet.highlighted)

    def perform_create(self, serializer):
        serializer.save(owner=self.request.user)

commonrepo/templates/elos/elos_network.html
{% extends "starter.html" %}

{% block title %}ELOs - {{object.name}}{% endblock %}
{% block page_title %}ELOs Netork{% endblock %}
{% block page_description %}Netork of "{{object.name}}"{% endblock %}
{% block page_breadcrumb %}ELO Network{% endblock %}

{% block content %}

<div class="row">
  <!-- Parent ELO-->  
  <!-- col -->
  <div class="col-md-12">
    <div class="box box-warning">
      <div class="box-header with-border">
        <h3 class="box-title">Parent ELOs of "{{object.name|truncatechars:90}}"</h3>
        <div class="box-tools pull-right">
          <button class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i></button>
          <button class="btn btn-box-tool" data-widget="remove"><i class="fa fa-times"></i></button>
        </div>
      </div><!-- /.box-header -->
      <div class="box-body">
        <div class="table-responsive">
          <table class="table no-margin">
            <thead>
              <tr>
                <th>ID</th>
                <th>Name</th>
                <th>Author</th>
                <th>Create Date</th>
                <th>Update Date</th>
                <th>Version</th>
                <th>Parent ELO</th>
                <th>Parent ELO version</th>
                <th>Type</th>
                <th>Public</th>
              </tr>
            </thead>
            <tbody>
              {% for parent_elo in parent_elos %}
                {% if parent_elo.is_public %}
                <tr>
                  <td><a href="{% url 'elos:elos-detail' parent_elo.id %}">{{parent_elo.id}}</a></td>
                  <td>{{parent_elo.name|truncatechars:30}}</td>
                  <td><a href="{% url 'users:detail' parent_elo.author %}">{{parent_elo.author}}</a></td>
                  <td>{{parent_elo.create_date|date:"SHORT_DATE_FORMAT"}}</td>
                  <td>{{parent_elo.update_date|timesince}}</td>
                  <td>{{parent_elo.version}}</td>
                  {% if elo.parent_elo.is_public %}
                    <td><a href="{% url 'elos:elos-detail' parent_elo.parent_elo_id %}">{{parent_elo.parent_elo|truncatechars:30}}</a></td>
                    <td>{{parent_elo.parent_elo_version}}</td>
                  {% else %}
                    {% if not elo.parent_elo.author == request.user and not request.user.is_staff %}
                      <td><span class="label bg-red">Private ELO</span></td>
                      <td><span class="label bg-red">Private ELO</span></td>
                    {% else %}
                      <td><a href="{% url 'elos:elos-detail' parent_elo.parent_elo.id %}">{{parent_elo.parent_elo|truncatechars:30}}</a></td>
                      <td>{{parent_elo.parent_elo_version}}</td>
                    {% endif %}
                  {% endif %}
                  <td>{{parent_elo.original_type}}</td>
                  <td>
                    {% if parent_elo.is_public %}
                      <span class="label label-primary">Yes</span>
                    {% else %}
                      <span class="label bg-red">No</span>
                    {% endif %}
                  </td>
                </tr>
                {% else %}
                <tr>
                  <td><span class="label bg-red">The target ELO is private</span></td>
                </tr>
                {% endif %}
              {% empty %}
                <tr>
                  <td>No parent ELOs yet.</td>
                </tr>
              {% endfor %}
            </tbody>
          </table>
        </div><!-- /.table-responsive -->
      </div><!-- /.box-body -->
    </div><!-- /.box -->
  </div><!-- /.col -->
  
  <!-- Original ELO-->
  <!-- col -->
  <div class="col-md-12">
    <div class="box box-primary">
      <div class="box-header with-border">
        <h3 class="box-title">Original ELO "{{object.name|truncatechars:90}}"</h3>
        <div class="box-tools pull-right">
          <button class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i></button>
          <button class="btn btn-box-tool" data-widget="remove"><i class="fa fa-times"></i></button>
        </div>
      </div><!-- /.box-header -->
      <div class="box-body">
        <div class="table-responsive">
          <table class="table no-margin">
            <thead>
              <tr>
                <th>ID</th>
                <th>Name</th>
                <th>Author</th>
                <th>Create Date</th>
                <th>Update Date</th>
                <th>Version</th>
                <th>Parent ELO</th>
                <th>Parent ELO version</th>
                <th>Type</th>
                <th>Public</th>
              </tr>
            </thead>
            <tbody>
              <tr>
                <td><a href="{% url 'elos:elos-detail' object.id %}">{{object.id}}</a></td>
                <td>{{object.name|truncatechars:30}}</td>
                <td><a href="{% url 'users:detail' object.author %}">{{object.author}}</a></td>
                <td>{{object.create_date|date:"SHORT_DATE_FORMAT"}}</td>
                <td>{{object.update_date|timesince}}</td>
                <td>{{object.version}}</td>
                {% if object.parent_elo.is_public %}
                  <td><a href="{% url 'elos:elos-detail' object.parent_elo_id %}">{{object.parent_elo|truncatechars:30}}</a></td>
                  <td>{{object.parent_elo_version}}</td>
                {% else %}
                  {% if not object.parent_elo.author == request.user and not request.user.is_staff %}
                    <td><span class="label bg-red">Private ELO</span></td>
                    <td><span class="label bg-red">Private ELO</span></td>
                  {% else %}
                    <td><a href="{% url 'elos:elos-detail' object.parent_elo_id %}">{{object.parent_elo|truncatechars:30}}</a></td>
                    <td>{{object.parent_elo_version}}</td>
                  {% endif %}
                {% endif %}
                <td>{{object.original_type}}</td>
                <td>
                  {% if object.is_public %}
                    <span class="label label-primary">Yes</span>
                  {% else %}
                    <span class="label bg-red">No</span>
                  {% endif %}
                </td>
              </tr>
            </tbody>
          </table>
        </div><!-- /.table-responsive -->
      </div><!-- /.box-body -->
      <div class="box-footer clearfix">
        <a href="{% url 'elos:elos-update' object.id %}" class="btn btn-sm btn-primary btn-flat pull-left">Update this ELO</a>
        <a href="{% url 'elos:elos-fork' object.id %}" class="btn btn-sm btn-primary btn-flat pull-left">Fork this ELO</a>
        <a href="{% url 'elos:elos-create' %}" class="btn btn-sm btn-warning btn-flat pull-left">Create a new ELO</a>
        <a href="{% url 'elos:elos-mylist' %}" class="btn btn-sm btn-default btn-flat pull-right">Back to My ELOs List</a>
      </div><!-- /.box-footer -->
    </div><!-- /.box -->
  </div><!-- /.col -->
  
  <!-- Child ELOs-->
  <!-- col -->
  <div class="col-md-12">
    <div class="box box-info">
      <div class="box-header with-border">
        <h3 class="box-title">Child ELOs of "{{object.name|truncatechars:90}}"</h3>
        <div class="box-tools pull-right">
          <button class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i></button>
          <button class="btn btn-box-tool" data-widget="remove"><i class="fa fa-times"></i></button>
        </div>
      </div><!-- /.box-header -->
      <div class="box-body">
        <div class="table-responsive">
          <table class="table no-margin">
            <thead>
              <tr>
                <th>ID</th>
                <th>Name</th>
                <th>Author</th>
                <th>Create Date</th>
                <th>Update Date</th>
                <th>Version</th>
                <th>Parent ELO</th>
                <th>Parent ELO version</th>
                <th>Type</th>
                <th>Public</th>
              </tr>
            </thead>
            <tbody>
              {% for child_elo in child_elos %}
                {% if child_elo.is_public %}
                <tr>
                  <td><a href="{% url 'elos:elos-detail' child_elo.id %}">{{child_elo.id}}</a></td>
                  <td>{{child_elo.name|truncatechars:30}}</td>
                  <td><a href="{% url 'users:detail' child_elo.author %}">{{child_elo.author}}</a></td>
                  <td>{{child_elo.create_date|date:"SHORT_DATE_FORMAT"}}</td>
                  <td>{{child_elo.update_date|timesince}}</td>
                  <td>{{child_elo.version}}</td>
                  {% if child_elo.parent_elo.is_public %}
                    <td><a href="{% url 'elos:elos-detail' child_elo.parent_elo_id %}">{{child_elo.parent_elo|truncatechars:30}}</a></td>
                    <td>{{child_elo.parent_elo_version}}</td>
                  {% else %}
                    {% if not child_elo.parent_elo.author == request.user and not request.user.is_staff %}
                      <td><span class="label bg-red">Private ELO</span></td>
                      <td><span class="label bg-red">Private ELO</span></td>
                    {% else %}
                      <td><a href="{% url 'elos:elos-detail' child_elo.parent_elo_id %}">{{child_elo.parent_elo|truncatechars:30}}</a></td>
                      <td>{{child_elo.parent_elo_version}}</td>
                    {% endif %}
                  {% endif %}
                  <td>{{child_elo.original_type}}</td>
                  <td>
                    {% if child_elo.is_public %}
                      <span class="label label-primary">Yes</span>
                    {% else %}
                      <span class="label bg-red">No</span>
                    {% endif %}
                  </td>
                </tr>
                {% else %}
                <tr>
                  <td><span class="label bg-red">The target ELO is private</span></td>
                </tr>
                {% endif %}
              {% empty %}
                <tr>
                  <td>No child ELOs yet.</td>
                </tr>
              {% endfor %}
            </tbody>
          </table>
        </div><!-- /.table-responsive -->
      </div><!-- /.box-body -->
    </div><!-- /.box -->
  </div><!-- /.col -->
</div><!-- /.row -->
{% endblock content %}